Algoritmo "CalcularMedia;"
Var
 num1, num2, num3, media: Real;
 
 Inicio
       Escreva("DIgite o primeiro Número: ")
       leia(num1)
       Escreva("Digite o segundo Número: ")
       Leia(num2)
       Escreva("Digite o terceiro Número: ")
       Leia(num3)
       
       // Calculando a média
       media <- (num1 + num2 + num3) / 3
       
       // exibindo a média na tela
       Escreva("A média dos números é: ", media)
       FimAlgoritmo
